name: Deploy Project
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: Building the project
        run: |
          cd /home/runner/work/controle-online/controle-online
          echo "export const ENTRYPOINT_LOCAL = 'https://api.controleonline.com'" > ./config/entrypoint.local.js
          echo "export const DOMAIN_LOCAL = location.host" > ./config/domain.local.js
          echo "const env = {\
          OAUTH_GOOGLE_CLIENT_ID:'${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}',\
          GMAPS_GOOGLE_CLIENT_ID:'${{ secrets.GMAPS_GOOGLE_CLIENT_ID }}',\
          NEW_RELIC:{\
            LICENSE_KEY:'${{ secrets.NEW_RELIC_LICENSE_KEY }}',\
            APPLICATION_ID:'${{ secrets.NEW_RELIC_APPLICATION_ID }}',\
            ACCOUNT_ID: '${{ secrets.NEW_RELIC_ACCOUNT_ID }}',\
            TRUST_KEY: '${{ secrets.NEW_RELIC_TRUST_KEY }}',\
            BEACON: '${{ secrets.NEW_RELIC_BEACON }}',\
            ERROR_BEACON: '${{ secrets.NEW_RELIC_ERROR_BEACON }}'\
          },\
          zoom: 0.70\
          };\
          module.exports = { env };\
          " > ./config/env.local.js
          git submodule update
          npm install --global yarn
          npm update
          yarn
          npx quasar build -m spa
      - name: Deploy
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "/home/runner/work/controle-online/controle-online/dist/spa"
          remoteDir: "~/public_html"
          forceSsl: true
