name: Deploy Project
on:
  push:
    branches: [develop, master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: Building the project dev
        run: |
          echo "const env = {\
          API_ENTRYPOINT: "https://api.dev.controleonline.com",\
          OAUTH_GOOGLE_CLIENT_ID:'${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}',\
          GMAPS_GOOGLE_CLIENT_ID:'${{ secrets.GMAPS_GOOGLE_CLIENT_ID }}',\
          NEW_RELIC:{\
            LICENSE_KEY:'${{ secrets.NEW_RELIC_LICENSE_KEY }}',\
            APPLICATION_ID:'${{ secrets.NEW_RELIC_APPLICATION_ID }}',\
            ACCOUNT_ID: '${{ secrets.NEW_RELIC_ACCOUNT_ID }}',\
            TRUST_KEY: '${{ secrets.NEW_RELIC_TRUST_KEY }}',\
            BEACON: '${{ secrets.NEW_RELIC_BEACON }}',\
            ERROR_BEACON: '${{ secrets.NEW_RELIC_ERROR_BEACON }}'\
          },\
          zoom: 0.70\
          };\
          module.exports = { env };\
          " > ./config/env.local.js
      
      - name: Update Submodules
        run: |
          git submodule update --recursive --init
          git submodule update --recursive --remote
      - name: Install Modules
        run: |
          npm install --global yarn
          yarn
      - name: Build
        run: |
          npx quasar build -m spa
      - name: Deploy
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.DEV_HOST }}
          user: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASS }}
          localDir: "./dist/spa"
          remoteDir: "~/public_html"
          forceSsl: false